### ISSUE TITLE
Fix Grafana setup

### ISSUE THREAD

**Issue by he-sk** [nebulastream/nebulastream-tutorial#35]
It is possible to provision the MQTT data source, so that it works out of the box.

```yaml
datasources:
- name: ...
  "jsonData": {
     "uri": "ws://mosquitto:9001"
   }
```
